### ISSUE TITLE
File lsp-mode is a symbolic link

### ISSUE THREAD

**Issue by mostevercxz** [MaskRay/Config#1]
I start using Emacs today because [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) does not autocomplete when  cquery and deoplete properly configured and started. Luckily, I googled `Emacs cquery` and found your article with your github link on it. 

I downloaded your Emacs config directory `.emacs.d` together with Spacemacs config file `.spacemacs`. After installing all the packages with command `emacs --insecure`, I restarted emacs with command `emacs --debug-init` and emacs shows error:
> Debugger entered--Lisp error: (void-variable c-c++modes)

I checked the Lisp code in file `.emacs.d/private/+my/my-code/packages.el` and I think the error may be related to the missing file `lsp-mode` under directory `.emacs.d/private/+my/my-code/local`(I know nothing about the Lisp programming language... ). Besides, I found other symbolic files using the command below:

```bash
giant@test:Config$ find . -type l -print0 | xargs -0 ls -al |grep Emacs
lrwxrwxrwx 1 giant giant 43 Jan 25 22:10 ./home/.emacs.d/private/+my/cquery/local/cquery -> ../../../../../../../Dev/Emacs/emacs-cquery
lrwxrwxrwx 1 giant giant 39 Jan 25 22:10 ./home/.emacs.d/private/+my/cquery/local/lsp-mode -> ../../../../../../../Dev/Emacs/lsp-mode
lrwxrwxrwx 1 giant giant 39 Jan 25 22:10 ./home/.emacs.d/private/+my/lsp/local/lsp-mode -> ../../../../../../../Dev/Emacs/lsp-mode
lrwxrwxrwx 1 giant giant 37 Jan 25 22:10 ./home/.emacs.d/private/+my/lsp/local/lsp-ui -> ../../../../../../../Dev/Emacs/lsp-ui
lrwxrwxrwx 1 giant giant 39 Jan 25 22:10 ./home/.emacs.d/private/+my/my-code/local/lsp-mode -> ../../../../../../../Dev/Emacs/lsp-mode
lrwxrwxrwx 1 giant giant 37 Jan 25 22:10 ./home/.emacs.d/private/+my/my-code/local/lsp-ui -> ../../../../../../../Dev/Emacs/lsp-ui
```

Could you please replace these symbolic files with their target files ? I'd like to check if Emacs still encounters errors with the right `lsp-mode` file.

Thank you for sharing such an amazing repo~
Best regards~

**Comment by MaskRay** [comment]
> Debugger entered--Lisp error: (void-variable c-c++modes)

This is defined in the +lang/c-c++ layer
`layers/+lang/c-c++/config.el:(defconst c-c++-modes '(c-mode c++-mode)`

I may have misspelled the name in an older version of my config.

> I checked the Lisp code in file .emacs.d/private/+my/my-code/packages.el and I think the error may be related to the missing file lsp-mode under directory .emacs.d/private/+my/my-code/local(I know nothing about the Lisp programming language... ). Besides, I found other symbolic files using the command below:


Yes. I have local emacs-cquery, lsp-mode and lsp-ui repositories in `~/Dev/Emacs/{emacs-cquery,lsp-ui,lsp-mode} and these `+my/cquery/local/{cquery,lsp-mode}` are symlinks pointing to them.

You can just replace `(lsp-mode :location local)` with `lsp-mode` in the package list.

**Comment by MaskRay** [comment]
I am now using ccls :)
