### ISSUE TITLE
`hydra/reg` for prev/next read/write heads not working with latest ccls

### ISSUE THREAD

**Issue by dfrib** [MaskRay/Config#2]
To begin with: thanks so much for your awesome work with `ccls`/`emacs-ccls`!

## Subject
The `hydra/reg` of [`.config/doom/config.el`](https://github.com/MaskRay/Config/blob/master/home/.config/doom/config.el#L194):
```lisp
(defhydra hydra/ref (evil-normal-state-map "x")
  "reference"
  ("d" lsp-ui-peek-find-definitions "next" :bind nil)
  ("n" (-let [(i . n) (lsp-ui-find-next-reference)]
             (if (> n 0) (message "%d/%d" i n))) "next")
  ("p" (-let [(i . n) (lsp-ui-find-prev-reference)]
             (if (> n 0) (message "%d/%d" i n))) "prev")
  ("R" (-let [(i . n) (lsp-ui-find-prev-reference
                       (lambda (x)
                         (/= (logand (gethash "role" x 0) 8) 0)))]
                         (if (> n 0) (message "read %d/%d" i n))) "prev read" :bind nil)
  ("r" (-let [(i . n) (lsp-ui-find-next-reference
                       (lambda (x)
                         (/= (logand (gethash "role" x 0) 8) 0)))]
                         (if (> n 0) (message "read %d/%d" i n))) "next read" :bind nil)
  ("W" (-let [(i . n) (lsp-ui-find-prev-reference
                       (lambda (x)
                         (/= (logand (gethash "role" x 0) 16) 0)))]
                         (if (> n 0) (message "write %d/%d" i n))) "prev write" :bind nil)
  ("w" (-let [(i . n) (lsp-ui-find-next-reference
                       (lambda (x)
                         (/= (logand (gethash "role" x 0) 16) 0)))]
                         (if (> n 0) (message "write %d/%d" i n))) "next write" :bind nil)
  )
```
### Issue?
Possibly I am doing something wrong in my config, but after I updated to [the latest `ccls`](https://github.com/MaskRay/ccls/commit/252b0d66064c23fabfad348d5b5cbcc8104d36cf) my non-evil version of the `hydra/reg` (see below) no longer works for the heads `R`, `r`, `W` and `w` (the lambda filters out all matches), possibly due to some changes in `ccls` regarding the `"role"` hash?

- Are you able to reproduce this issue?

### Minor issue
The messages that display _"i out of n match"_ are off by one. The segments
```lisp
(message "%d/%d" i n)
```
should (probably) be replaced by
```list
(message "%d/%d" (+ i 1) n)
```
I was planning to submit a pull request for this, but as I have no idea regarding how to correct (if even broken) the issue above, I waited with this.

### Details: my nearly identical non-evil hydra
```lisp
(defhydra +mr/hydra-lsp-traverse (:hint nil)
  "Traverse references"
  ("d" lsp-ui-peek-find-definitions "next" :bind nil)
  ("n" (-let [(i . n) (lsp-ui-find-next-reference)]
             (if (> n 0) (message "%d/%d" (+ i 1) n))) "next")
  ("p" (-let [(i . n) (lsp-ui-find-prev-reference)]
             (if (> n 0) (message "%d/%d" (+ i 1) n))) "prev")
  ("R" (-let [(i . n) (lsp-ui-find-prev-reference
                       (lambda (x)
                         (/= (logand (gethash "role" x 0) 8) 0)))]
                         (if (> n 0) (message "read %d/%d" (+ i 1) n))) "prev read" :bind nil)
  ("r" (-let [(i . n) (lsp-ui-find-next-reference
                       (lambda (x)
                         (/= (logand (gethash "role" x 0) 8) 0)))]
                         (if (> n 0) (message "read %d/%d" (+ i 1) n))) "next read" :bind nil)
  ("W" (-let [(i . n) (lsp-ui-find-prev-reference
                       (lambda (x)
                         (/= (logand (gethash "role" x 0) 16) 0)))]
                         (if (> n 0) (message "write %d/%d" (+ i 1) n))) "prev write" :bind nil)
  ("w" (-let [(i . n) (lsp-ui-find-next-reference
                       (lambda (x)
                         (/= (logand (gethash "role" x 0) 16) 0)))]
                         (if (> n 0) (message "write %d/%d" (+ i 1) n))) "next write" :bind nil)
  ("q" nil "stop")
  )
```

**Comment by MaskRay** [comment]
Thanks.

> The messages that display "i out of n match" are off by one. The segments

It is because I'm used to 0-based counting. I'm ok with either 0-based or
1-based but I'm lazy to add the extra `+1` here and there (I was reading some
Lua articles before I typed this...)

> my non-evil version of the hydra/reg (see below) no longer works for the heads R, r, W and w (the lambda filters out all matches), possibly due to some changes in ccls regarding the "role" hash?

This is an issue which I did not notice when I pushed this commit

    Date:   Thu Oct 4 16:13:30 2018 -0700

        Redesign SymbolRef, Ref, Use
    
        Remove lsLocationEx

`lsLocationEx` encodes `Role role;` but `lsLocation` (language server protocol) does not, thus the hydra "next read" cannot find the next read.

I missed this because I use `xn` `xp` a lot but rarely `xr` `xw`. Under the hood, ccls `Role::Read` `Role::Write` are only relevant for POD types and a few other simple cases in `clang/lib/Index`.

For this example `func_ptr = func;`, the `func` on the right hand side does not have the `clang::SymbolRole::AddressOf` bit, while `func_ptr = &func;` has. https://github.com/llvm-mirror/clang/tree/master/include/clang/Index/IndexSymbol.h

When I really want to find references with `Role::Read` bit, I use:

```elisp
;; References w/ Role::Read
(defun ccls/references-read ()
  (interactive)
  (lsp-ui-peek-find-custom
   'read "textDocument/references"
   (plist-put (lsp--text-document-position-params) :context
              '(:role 8))))

;; References w/ Role::Write
(defun ccls/references-write ()
  (interactive)
  (lsp-ui-peek-find-custom
   'write "textDocument/references"
   (plist-put (lsp--text-document-position-params) :context
              '(:role 16))))
```

"next read" is still possible: `textDocument/references` accepts `context.role` to filter results. I think it can be used to do the job.
(As you can see, lsp-ui-peek-next-reference is a hack to retrieve the next reference (it is very low efficient))

**Comment by MaskRay** [comment]
Fixed

**Comment by dfrib** [comment]
Thanks for the quick and detailed reply!

> It is because I'm used to 0-based counting. I'm ok with either 0-based or
> 1-based but I'm lazy to add the extra +1 here and there (I was reading some
> Lua articles before I typed this...)

Sorry if I was a bit unclear: the off by one I mentioned does not effect any of the functionality, but displays `current reference/total references` with an off by one error for the former as the latter, `n`, seems to always display the number of hits (`10` hits -> displays total count `10`, not `9`). 

E.g. when I am traversing `lsp-ui-find-next-reference` with `xn` for, say, `10` references, then the traversal status will display in `0/10` through `9/10` (never `10/10`) in the minibuffer, instead of any of the valid alternatives:
- `1/10` through `10/10`, or 
- `0/9` through `9/9`.

---

> "next read" is still possible: textDocument/references accepts context.role to filter results. I think it can be used to do the job.

~~I didn't follow all the details of your post, but when I make use of `:context role` fix of the [emacs: lsp-ui-find-prev-reference](https://github.com/MaskRay/Config/commit/b2bcade88d2ab75cf7769af3d7723cba4ade616f) patch, I get prompted with the following errors:~~

```lisp
; xr and xR
Invalid function: (:context (:role 8))
; xw and xW
Invalid function: (:context (:role 16))
```
~~Do I need to change anything else beyond the corrections to the hydra? Did you verify that you can traverse e.g. writes with `xw` after the fix? (Maybe I am missing what is possible here, see the final section below).~~

---

> I missed this because I use xn xp a lot but rarely xr xw.

I generally also mainly use `xn` and `xp`, but sometimes I find `xw` and `xW` useful: prior to my last update of `ccls` I could use it to find all places where e.g. member variables of particular types was mutated (without caring about all the non-mutated reads). I'm think this was valid for all types (not just POD members),~~ but maybe that was deprecated by the removal of `lsLocationEx`?~~

> Under the hood, ccls Role::Read Role::Write are only relevant for POD types and a few other simple cases in clang/lib/Index

~~Maybe this answers my question: the behaviour before the removal of `IsLocationEx` (which used custom encoding) will not be possibly (natively in LSP) anymore after the removal? Or can I use some alternative approach for my common use case of finding mutations of a member variable at point?~~

**Comment by dfrib** [comment]
Never mind my the last two segments of my comment above (the first segment regarding the off by one might still be useful though, if you feel that `0/10` through `9/10` would bother you :) ): 
- I see I have not updated `lsp-ui` accordingly (as per your patch [lsp-ui-find-{next,prev}-reference: pass extra params ...](https://github.com/emacs-lsp/lsp-ui/commit/06b0406c8b4447455435b5900ee9b7cce034f3f3)).

Using the update `lsp-ui`, the fix works like a charm! :+1:

**Comment by MaskRay** [comment]
> Sorry if I was a bit unclear: the off by one I mentioned does not effect any of the functionality, but displays `current reference/total references` with an off by one error for the former as the latter, `n`, seems to always display the number of hits (`10` hits -> displays total count `10`, not `9`).
> 
> E.g. when I am traversing `lsp-ui-find-next-reference` with `xn` for, say, `10` references, then the traversal status will display in `0/10` through `9/10` (never `10/10`) in the minibuffer, instead of any of the valid alternatives:
> 
> * `1/10` through `10/10`, or
> * `0/9` through `9/9`.

Yeah it will be displayed as `0/10` through `9/10`. `1/10` through `10/10` is
probably more natural but I'm fine with either display...

> > "next read" is still possible: textDocument/references accepts context.role to filter results. I think it can be used to do the job.
> 
> I didn't follow all the details of your post, but when I make use of `:context role` fix of the [emacs: lsp-ui-find-prev-reference](https://github.com/MaskRay/Config/commit/b2bcade88d2ab75cf7769af3d7723cba4ade616f) patch, I get prompted with the following errors:
> 
> ```lisp
> ; xr and xR
> Invalid function: (:context (:role 8))
> ; xw and xW
> Invalid function: (:context (:role 16))
> ```

I pushed a fix to lsp-ui and you need to update your lsp-ui

> I generally also mainly use `xn` and `xp`, but sometimes I find `xw` and `xW` useful: prior to my last update of `ccls` I could use it to find all places where e.g. member variables of particular types was mutated (without caring about all the non-mutated reads). I'm think this was valid for all types (not just POD members),~~ but maybe that was deprecated by the removal of `lsLocationEx`?~~

`(lsp-ui-find-prev-reference '(:context (:role 8)))` (the parameter was no
longer a function) should work if you update your lsp-ui

The removal of `lsLocationEx` is irrelevant with the updated config.

> 
> > Under the hood, ccls Role::Read Role::Write are only relevant for POD types and a few other simple cases in clang/lib/Index
> 
> Maybe this answers my question: the behaviour before the removal of `IsLocationEx` (which used custom encoding) will not be possibly (natively in LSP) anymore after the removal? Or can I use some alternative approach for my common use case of finding mutations of a member variable at point?

Emacs json parsing and processing is slow. So getting rid of some unused fields in `IsLocationEx` in favor of `lsLocation` improves the performance...

**Comment by dfrib** [comment]
Yep it worked great once I updated `lsp-ui` (which I initially missed), thanks again :+1:

**Comment by MaskRay** [comment]
Speaking of performance, does `:use-native-json t` (use Emacs 27) make you feel faster? 
https://github.com/MaskRay/emacs-ccls/commits/json

Build instructions: https://github.com/MaskRay/Config/wiki#emacs

**Comment by dfrib** [comment]
I just did the switch from `rtags`/`cmake-ide` to `ccls` this weekend, as part of migrating to a non-evil DOOM Emacs configuration, so I haven't really had the time to test out `ccls` beyond configuration yet.

Will do the switch at my work machine tomorrow, where I'll get a better chance to test it out. I'll try both with and without `:use-native-json t` and get back to you.

**Comment by MaskRay** [comment]
Thanks! You are also welcome to join the gitter channel https://gitter.im/ccls-project/ccls
